"""initial schema

Revision ID: 2865e06dda5f
Revises: 
Create Date: 2026-03-20 01:06:40.533509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2865e06dda5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.Enum('OIL_GAS', 'AGRICULTURE', 'MINING', 'AVIATION', 'SHIPPING', 'ENERGY', 'MANUFACTURING', name='companysector'), nullable=False),
    sa.Column('country_of_registration', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('esg_score', sa.Float(), nullable=True),
    sa.Column('annual_emissions_mtonnes', sa.Float(), nullable=True),
    sa.Column('is_paris_signatory', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organisations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('org_type', sa.Enum('GRASSROOTS', 'NGO', 'LEGAL_COALITION', 'INDIGENOUS_GROUP', 'INTERNATIONAL', 'POLITICAL_PARTY', name='orgtype'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('founding_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('threat_type', sa.Enum('PIPELINE', 'DEFORESTATION', 'AIR_POLLUTION', 'MINING', 'OFFSHORE_DRILLING', name='threattype'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'UNDER_CONSTRUCTION', 'OPERATIONAL', 'SUSPENDED', 'CANCELLED', name='threatstatus'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('estimated_co2_impact_tonnes', sa.Float(), nullable=True),
    sa.Column('land_area_affected_km2', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CONTRIBUTOR', 'READER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.Enum('LEGAL_CHALLENGE', 'PROTEST', 'PETITION', 'LOBBYING', 'DIRECT_ACTION', 'MEDIA_CAMPAIGN', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'WON', 'LOST', 'ONGOING', 'SUSPENDED', name='campaignstatus'), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('threat_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('outcome_summary', sa.String(), nullable=True),
    sa.Column('signatures_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_companies',
    sa.Column('threat_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'INVESTOR', 'CONTRACTOR', 'FINANCIER', name='companyrole'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('threat_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_companies')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('threats')
    op.drop_table('organisations')
    op.drop_table('companies')
    # ### end Alembic commands ###
